# NumPy, Pandas & Bokeh 

## Learning Goals
* NumPy: creating a matrix
* Pandas: creating dataframes

## NumPy

NumPy is used to construct N-dimensional array objects.

### Creating an array

In [6]:
import numpy as np
# arange(n) creates row of integers of length n. reshape(M,N) converts the list to a matrix of size MxN
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
# creates array of 0-9 numbers
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
alist = [1,2,3]
type(alist)

list

In [10]:
np.array(alist)

array([1, 2, 3])

In [13]:
print a.mean() # avg of whole matrix
print a.mean(0) # avg per col
print a.mean(1) # avg per row

12.0
[ 10.  11.  12.  13.  14.]
[  2.   7.  12.  17.  22.]


In [14]:
compa = np.arange(30).reshape(5,3,2)
compa

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [15]:
print compa.shape
print compa.ndim
print compa.dtype

(5, 3, 2)
3
int64


In [22]:
compa[3,:,1]

array([19, 21, 23])

In [23]:
compa[0,0,0]

0

In [24]:
#Create a randomized array
rm = np.random.rand(5,5)
rm

array([[ 0.23007657,  0.76731656,  0.99136506,  0.93531216,  0.86887176],
       [ 0.59875985,  0.79216882,  0.08994716,  0.51864617,  0.62974096],
       [ 0.09059415,  0.2494754 ,  0.07176685,  0.06224635,  0.43810785],
       [ 0.33625933,  0.14639543,  0.33145226,  0.49275132,  0.47707045],
       [ 0.13415292,  0.39061967,  0.28313511,  0.30000977,  0.03880792]])

In [30]:
print rm.mean()
print rm.mean(0)
print rm.mean(1)
print np.median(rm)
print rm.var()
print rm.std()

0.410601994257
[ 0.27796856  0.46919518  0.35353329  0.46179316  0.49051979]
[ 0.75858842  0.52585259  0.18243812  0.35678576  0.22934508]
0.336259327148
0.0811017637266
0.284783713942


## Pandas

In [32]:
import pandas as pd

data = pd.read_csv('../data/titanic.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [33]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [34]:
data[data.Age > 65]

PassengerId  Survived  Pclass                                  Name  \
33            34         0       2                 Wheadon, Mr. Edward H   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2           Mitchell, Mr. Henry Michael   
745          746         0       1          Crosby, Capt. Edward Gifford   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
33   male  66.0      0      0  C.A. 24579  10.5000   NaN        S  
96   male  71.0      0      0    PC 17754  34.6542    A5        C  
116  male  70.5      0      0      370369   7.7500   NaN        Q  
493  male  71.0      0      0    PC 17609  49.5042   NaN        C  
630  male  80.0      0      0       27042  30.0000   A23        S  
672  male  70.0      0      0  C.A. 24580  10.5000   NaN        S  
745  male  70.0      1      1   WE/P 5735  71.0000   B22        S  
851  male  74.0      0      0      347060   7.7750   NaN        S

In [35]:
data[(data.Age == 11) & (data.SibSp == 5)]

PassengerId  Survived  Pclass                                Name   Sex  \
59           60         0       3  Goodwin, Master. William Frederick  male   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked  
59  11.0      5      2  CA 2144  46.9   NaN        S

In [36]:
data[(data.Age == 11) | (data.SibSp == 5)]

PassengerId  Survived  Pclass                                 Name  \
59            60         0       3   Goodwin, Master. William Frederick   
71            72         0       3           Goodwin, Miss. Lillian Amy   
386          387         0       3      Goodwin, Master. Sidney Leonard   
480          481         0       3       Goodwin, Master. Harold Victor   
542          543         0       3    Andersson, Miss. Sigrid Elisabeth   
683          684         0       3          Goodwin, Mr. Charles Edward   
731          732         0       3             Hassan, Mr. Houssein G N   
802          803         1       1  Carter, Master. William Thornton II   

        Sex   Age  SibSp  Parch   Ticket      Fare    Cabin Embarked  
59     male  11.0      5      2  CA 2144   46.9000      NaN        S  
71   female  16.0      5      2  CA 2144   46.9000      NaN        S  
386    male   1.0      5      2  CA 2144   46.9000      NaN        S  
480    male   9.0      5      2  CA 2144   46.9000      NaN        S  
542  female  11.0      4      2   347082   31.2750      NaN        S  
683    male  14.0      5      2  CA 2144   46.9000      NaN        S  
731    male  11.0      0      0     2699   18.7875      NaN        C  
802    male  11.0      1      2   113760  120.0000  B96 B98        S

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [38]:
data[data.Age.isnull()]

PassengerId  Survived  Pclass  \
5              6         0       3   
17            18         1       2   
19            20         1       3   
26            27         0       3   
28            29         1       3   
29            30         0       3   
31            32         1       1   
32            33         1       3   
36            37         1       3   
42            43         0       3   
45            46         0       3   
46            47         0       3   
47            48         1       3   
48            49         0       3   
55            56         1       1   
64            65         0       1   
65            66         1       3   
76            77         0       3   
77            78         0       3   
82            83         1       3   
87            88         0       3   
95            96         0       3   
101          102         0       3   
107          108         1       3   
109          110         1       3   
121          122         0       3   
126          127         0       3   
128          129         1       3   
140          141         0       3   
154          155         0       3   
..           ...       ...     ...   
718          719         0       3   
727          728         1       3   
732          733         0       2   
738          739         0       3   
739          740         0       3   
740          741         1       1   
760          761         0       3   
766          767         0       1   
768          769         0       3   
773          774         0       3   
776          777         0       3   
778          779         0       3   
783          784         0       3   
790          791         0       3   
792          793         0       3   
793          794         0       1   
815          816         0       1   
825          826         0       3   
826          827         0       3   
828          829         1       3   
832          833         0       3   
837          838         0       3   
839          840         1       1   
846          847         0       3   
849          850         1       1   
859          860         0       3   
863          864         0       3   
868          869         0       3   
878          879         0       3   
888          889         0       3   

                                               Name     Sex  Age  SibSp  \
5                                  Moran, Mr. James    male  NaN      0   
17                     Williams, Mr. Charles Eugene    male  NaN      0   
19                          Masselmani, Mrs. Fatima  female  NaN      0   
26                          Emir, Mr. Farred Chehab    male  NaN      0   
28                    O'Dwyer, Miss. Ellen "Nellie"  female  NaN      0   
29                              Todoroff, Mr. Lalio    male  NaN      0   
31   Spencer, Mrs. William Augustus (Marie Eugenie)  female  NaN      1   
32                         Glynn, Miss. Mary Agatha  female  NaN      0   
36                                 Mamee, Mr. Hanna    male  NaN      0   
42                              Kraeff, Mr. Theodor    male  NaN      0   
45                         Rogers, Mr. William John    male  NaN      0   
46                                Lennon, Mr. Denis    male  NaN      1   
47                        O'Driscoll, Miss. Bridget  female  NaN      0   
48                              Samaan, Mr. Youssef    male  NaN      2   
55                                Woolner, Mr. Hugh    male  NaN      0   
64                            Stewart, Mr. Albert A    male  NaN      0   
65                         Moubarek, Master. Gerios    male  NaN      1   
76                                Staneff, Mr. Ivan    male  NaN      0   
77                         Moutal, Mr. Rahamin Haim    male  NaN      0   
82                   McDermott, Miss. Brigdet Delia  female  NaN      0   
87                    Slocovski, Mr. Selman Francis    male  NaN      0  

In [41]:
data.Age[data.Age.isnull()].fillna(0)

5      0.0
17     0.0
19     0.0
26     0.0
28     0.0
29     0.0
31     0.0
32     0.0
36     0.0
42     0.0
45     0.0
46     0.0
47     0.0
48     0.0
55     0.0
64     0.0
65     0.0
76     0.0
77     0.0
82     0.0
87     0.0
95     0.0
101    0.0
107    0.0
109    0.0
121    0.0
126    0.0
128    0.0
140    0.0
154    0.0
      ... 
718    0.0
727    0.0
732    0.0
738    0.0
739    0.0
740    0.0
760    0.0
766    0.0
768    0.0
773    0.0
776    0.0
778    0.0
783    0.0
790    0.0
792    0.0
793    0.0
815    0.0
825    0.0
826    0.0
828    0.0
832    0.0
837    0.0
839    0.0
846    0.0
849    0.0
859    0.0
863    0.0
868    0.0
878    0.0
888    0.0
Name: Age, dtype: float64

In [46]:
avg_age = data.Age[data.Age.notnull()].mean()
data.Age.fillna(avg_age)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
5      29.699118
6      54.000000
7       2.000000
8      27.000000
9      14.000000
10      4.000000
11     58.000000
12     20.000000
13     39.000000
14     14.000000
15     55.000000
16      2.000000
17     29.699118
18     31.000000
19     29.699118
20     35.000000
21     34.000000
22     15.000000
23     28.000000
24      8.000000
25     38.000000
26     29.699118
27     19.000000
28     29.699118
29     29.699118
         ...    
861    21.000000
862    48.000000
863    29.699118
864    24.000000
865    42.000000
866    27.000000
867    31.000000
868    29.699118
869     4.000000
870    26.000000
871    47.000000
872    33.000000
873    47.000000
874    28.000000
875    15.000000
876    20.000000
877    19.000000
878    29.699118
879    56.000000
880    25.000000
881    33.000000
882    22.000000
883    28.000000
884    25.000000
885    39.000000
886    27.000000
887    19.000000
888    29.6991

In [47]:
data.Age[data.Age.notnull()].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [48]:
data.Age.fillna(np.random.normal(29.7,14.5),inplace=True)

In [49]:
data.Age.fillna(np.random.normal(29.7,14.5)).describe()

count    891.000000
mean      30.407180
std       13.079644
min        0.420000
25%       22.000000
50%       32.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [51]:
data.groupby('Survived')['Age'].mean()

Survived
0    31.226646
1    29.091720
Name: Age, dtype: float64

In [54]:
data.groupby(['Survived','Pclass'])['PassengerId'].count()

Survived  Pclass
0         1          80
          2          97
          3         372
1         1         136
          2          87
          3         119
Name: PassengerId, dtype: int64